# Generated by Django 5.0.1 on 2024-02-02 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.CharField(max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comprovante_pagamento', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inscrito', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('idade', models.IntegerField(default=0)),
                ('dt_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 1')),
                ('telefone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, default='-', max_length=50, verbose_name='Responsável (Se menor de 18 anos)')),
                ('cep', models.CharField(blank=True, max_length=11, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, default=0, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco_responsável', models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Responsável legal', 'Responsavel legal')], max_length=50, null=True, verbose_name='Parentesco')),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Namorando', 'Namorando')], max_length=20)),
                ('valor_inscricao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Pagamento parcelado', 'Pagamento parcelado')], default='Pagamento parcelado', max_length=50)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.pagamento')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
