# Generated by Django 5.0.1 on 2024-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inscrito', models.CharField(max_length=50)),
                ('idade', models.IntegerField(default=0)),
                ('responsável', models.CharField(max_length=50)),
                ('parentesco_responsável', models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Responsável legal', 'Responsavel legal')], max_length=50, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Namorando', 'Namorando')], default='Em avaliação', max_length=20)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Pagamento parcelado', 'Pagamento parcelado')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprovante_pagamento', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
