# Generated by Django 5.0.1 on 2024-01-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='pagamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subscription.pagamento'),
            preserve_default=False,
        ),
    ]
