# Generated by Django 5.0.1 on 2024-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='dt_inscricao',
            field=models.DateTimeField(),
        ),
    ]
