# Generated by Django 5.0.1 on 2024-02-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_inscricoes_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricoes',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='user',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='Inscrito',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='subscription.inscricoes'),
            preserve_default=False,
        ),
    ]
