# Generated by Django 5.0.1 on 2024-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_inscricoes_dt_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='dt_inscricao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
