# Generated by Django 5.0.1 on 2024-01-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_inscricoes_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricoes',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
