# Generated by Django 5.0.1 on 2024-01-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_inscricoes_dt_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
