# Generated by Django 5.0.1 on 2024-02-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_inscricoes_pagamento_remove_pagamento_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='Inscrito',
            new_name='inscrito',
        ),
    ]
