# Generated by Django 5.0.1 on 2024-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_inscrito_pagamento_inscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
