# Generated by Django 5.0.1 on 2024-01-31 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_inscricoes_valor_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='dt_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
