# Generated by Django 5.0.1 on 2024-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_inscricoes_dt_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='responsável',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Responsável (Se menor de 18 anos)'),
        ),
    ]
