# Generated by Django 5.0.1 on 2024-02-02 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_pagamento_inscrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Namorando', 'Namorando')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
