# Generated by Django 5.0.1 on 2024-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_inscricoes_responsável'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricoes',
            name='responsável',
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='responsavel',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Responsável (Se menor de 18 anos)'),
        ),
    ]
