# Generated by Django 5.0.1 on 2024-02-02 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_inscricoes_estado_civil_alter_inscricoes_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
