# Generated by Django 5.0.1 on 2024-02-02 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_pagamento_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
