# Generated by Django 5.0.1 on 2024-02-03 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_pagamento_inscrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='inscrito',
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='subscription.pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_pagamento',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
