# Generated by Django 5.0.1 on 2024-02-03 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_remove_pagamento_inscrito_inscricoes_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricoes',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='inscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='subscription.inscricoes'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
