# Generated by Django 5.0.1 on 2024-02-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_inscricoes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='inscricao',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='subscription.inscricoes'),
            preserve_default=False,
        ),
    ]
