# Generated by Django 5.0.1 on 2024-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_pagamento_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_pagamento',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
