# Generated by Django 5.0.1 on 2024-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_inscricoes_total_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='nome_inscrito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do cônjuge'),
        ),
    ]
