# Generated by Django 5.0.1 on 2024-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_alter_inscricoes_nome_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='conjuge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='nome_inscrito',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome completo'),
            preserve_default=False,
        ),
    ]
