# Generated by Django 5.0.1 on 2024-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0023_inscricoes_conjuge_alter_inscricoes_nome_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='idade_conjuge',
            field=models.IntegerField(default=0),
        ),
    ]
