# Generated by Django 5.0.1 on 2024-02-14 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0025_alter_inscricoes_idade_conjuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='dt_inscricao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data de inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='idade_conjuge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Idade do cônjuge'),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='responsavel',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Responsável'),
        ),
    ]
