# Generated by Django 5.0.1 on 2024-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0026_alter_inscricoes_dt_inscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável'),
        ),
    ]
