# Generated by Django 5.0.1 on 2024-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0027_alter_inscricoes_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Pendente de conferência', 'Pendente de conferência'), ('Reprovado', 'Reprovado')], default='Pendente de conferência', max_length=50),
        ),
    ]
